twig:
    paths: 
        '%kernel.project_dir%/templates/Admin': Admin
        '%kernel.project_dir%/templates/Web': Web
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']

