vich_uploader:
    db_driver: orm

    mappings:
       albums:
           uri_prefix: /Web/img/albums/
           upload_destination: '%kernel.project_dir%/public/Web/img/albums/'
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true